class_name Paths

const GAME_ROOT_PATH: String = "res://src/scenes/game_root/game_root.tscn"
const START_PATH: String = "res://src/scenes/start/start.tscn"
const MAIN_PATH: String = "res://src/scenes/main/main.tscn"
const INGAME_PATH: String = "res://src/scenes/ingame/ingame.tscn"
const CHARACTER_BASE: String = "res://src/scenes/character_base/character_base.tscn"
const PROJECTILE: String = "res://src/scenes/projectile/projectile.tscn"

const CHARACTER_DATA_TEST1: String = "res://src/resources/characters/test1/data.tres"
const CHARACTER_DATA_AATROX: String = "res://src/resources/characters/aatrox/data.tres"
const CHARACTER_DATA_DARIUS: String = "res://src/resources/characters/darius/data.tres"
const CHARACTER_DATA_SYLAS: String = "res://src/resources/characters/sylas/data.tres"

const ITEM_DATA_ECLIPSE: String = "res://src/resources/items/eclipse/data.tres"
const ITEM_DATA_TRINITY_FORCE: String = "res://src/resources/items/trinity_force/data.tres"
const ITEM_DATA_BLADE_OF_THE_RUINED_KING: String = "res://src/resources/items/blade_of_the_ruined_king/data.tres"
const ITEM_DATA_SPEAR_OF_SHOJIN: String = "res://src/resources/items/spear_of_shojin/data.tres"
const ITEM_DATA_THE_BLACK_CLEAVER: String = "res://src/resources/items/the_black_cleaver/data.tres"
const ITEM_DATA_SUNDERED_SKY: String = "res://src/resources/items/sundered_sky/data.tres"
const ITEM_DATA_STERAKS_GAGE: String = "res://src/resources/items/steraks_gage/data.tres"
const ITEM_DATA_DEATHS_DANCE: String = "res://src/resources/items/deaths_dance/data.tres"
const ITEM_DATA_GUARDIAN_ANGEL: String = "res://src/resources/items/guardian_angel/data.tres"

const ITEM_DATA_NASHORS_TOOTH: String = "res://src/resources/items/nashors_tooth/data.tres"
const ITEM_DATA_LICH_BANE: String = "res://src/resources/items/lich_bane/data.tres"
const ITEM_DATA_RABADONS_DEATHCAP: String = "res://src/resources/items/rabadons_deathcap/data.tres"
const ITEM_DATA_SHADOWFLAME: String = "res://src/resources/items/shadowflame/data.tres"
const ITEM_DATA_VOID_STAFF: String = "res://src/resources/items/void_staff/data.tres"
const ITEM_DATA_LIANDRYS_TORMENT: String = "res://src/resources/items/liandrys_torment/data.tres"
const ITEM_DATA_SCEPER_OF_BONKING: String = "res://src/resources/items/scepter_of_bonking/data.tres"
const ITEM_DATA_MORELLONOMICON: String = "res://src/resources/items/morellonomicon/data.tres"
const ITEM_DATA_MALIGNANCE: String = "res://src/resources/items/malignance/data.tres"
const ITEM_DATA_STORMSURGE: String = "res://src/resources/items/stormsurge/data.tres"

const RUNE_DATA_PRESS_THE_ATTACK: String = "res://src/resources/runes/press_the_attack/data.tres"
const RUNE_DATA_LETHAL_TEMPO: String = "res://src/resources/runes/lethal_tempo/data.tres"
const RUNE_DATA_FLEET_FOOTWORK: String = "res://src/resources/runes/fleet_footwork/data.tres"
const RUNE_DATA_CONQUEROR: String = "res://src/resources/runes/conqueror/data.tres"
const RUNE_DATA_ELECTROCUTE: String = "res://src/resources/runes/electrocute/data.tres"
