class_name Paths

const GAME_ROOT_PATH: String = "res://src/scenes/game_root/game_root.tscn"
const START_PATH: String = "res://src/scenes/start/start.tscn"
const MAIN_PATH: String = "res://src/scenes/main/main.tscn"
const INGAME_PATH: String = "res://src/scenes/ingame/ingame.tscn"
const CHARACTER_BASE: String = "res://src/scenes/character_base/character_base.tscn"
const PROJECTILE: String = "res://src/scenes/projectile/projectile.tscn"
const AREA: String = "res://src/scenes/area/area.tscn"

const CHARACTER_DATA_TEST1: String = "res://src/resources/characters/test1/data.tres"
const CHARACTER_DATA_AATROX: String = "res://src/resources/characters/aatrox/data.tres"
const CHARACTER_DATA_DARIUS: String = "res://src/resources/characters/darius/data.tres"
const CHARACTER_DATA_SYLAS: String = "res://src/resources/characters/sylas/data.tres"
const CHARACTER_DATA_ASHE: String = "res://src/resources/characters/ashe/data.tres"
const CHARACTER_DATA_YONE: String = "res://src/resources/characters/yone/data.tres"
const CHARACTER_DATA_ZED: String = "res://src/resources/characters/zed/data.tres"

const ITEM_DATA_BERSERKERS_GREAVES: String = "res://src/resources/items/berserkers_greaves/data.tres"

const ITEM_DATA_ECLIPSE: String = "res://src/resources/items/eclipse/data.tres"
const ITEM_DATA_TRINITY_FORCE: String = "res://src/resources/items/trinity_force/data.tres"
const ITEM_DATA_BLADE_OF_THE_RUINED_KING: String = "res://src/resources/items/blade_of_the_ruined_king/data.tres"
const ITEM_DATA_SPEAR_OF_SHOJIN: String = "res://src/resources/items/spear_of_shojin/data.tres"
const ITEM_DATA_BLACK_CLEAVER: String = "res://src/resources/items/black_cleaver/data.tres"
const ITEM_DATA_SUNDERED_SKY: String = "res://src/resources/items/sundered_sky/data.tres"
const ITEM_DATA_STERAKS_GAGE: String = "res://src/resources/items/steraks_gage/data.tres"
const ITEM_DATA_DEATHS_DANCE: String = "res://src/resources/items/deaths_dance/data.tres"
const ITEM_DATA_GUARDIAN_ANGEL: String = "res://src/resources/items/guardian_angel/data.tres"
const ITEM_DATA_EXPERIMENTAL_HEXPLATE: String = "res://src/resources/items/experimental_hexplate/data.tres"
const ITEM_DATA_ENDLESS_HUNGER: String = "res://src/resources/items/endless_hunger/data.tres"
const ITEM_DATA_WITS_END: String = "res://src/resources/items/wits_end/data.tres"
const ITEM_DATA_MANAMUNE: String = "res://src/resources/items/manamune/data.tres"
const ITEM_DATA_MURAMANA: String = "res://src/resources/items/muramana/data.tres"
const ITEM_DATA_MAW_OF_MALMORTIUS: String = "res://src/resources/items/maw_of_malmortius/data.tres"
const ITEM_DATA_CHEMPUNK_CHAINSWORD: String = "res://src/resources/items/chempunk_chainsword/data.tres"
const ITEM_DATA_OVERLORDS_BLOODMAIL: String = "res://src/resources/items/overlords_bloodmail/data.tres"

const ITEM_DATA_THE_COLLECTOR: String = "res://src/resources/items/the_collector/data.tres"
const ITEM_DATA_HEXOPTICS_C44: String = "res://src/resources/items/hexoptics_c44/data.tres"
const ITEM_DATA_KRAKEN_SLAYER: String = "res://src/resources/items/kraken_slayer/data.tres"
const ITEM_DATA_PHANTOM_DANCER: String = "res://src/resources/items/phantom_dancer/data.tres"
const ITEM_DATA_RUNAANS_HURRICANE: String = "res://src/resources/items/runaans_hurricane/data.tres"
const ITEM_DATA_RAPID_FIRECANNON: String = "res://src/resources/items/rapid_firecannon/data.tres"
const ITEM_DATA_NAVORI_FLICKERBLADE: String = "res://src/resources/items/navori_flickerblade/data.tres"
const ITEM_DATA_FIENDHUNTER_BOLTS: String = "res://src/resources/items/fiendhunter_bolts/data.tres"
const ITEM_DATA_LORD_DOMINIKS_REGARDS: String = "res://src/resources/items/lord_dominiks_regards/data.tres"
const ITEM_DATA_MORTAL_REMINDER: String = "res://src/resources/items/mortal_reminder/data.tres"
const ITEM_DATA_TERMINUS: String = "res://src/resources/items/terminus/data.tres"
const ITEM_DATA_GUINSOOS_RAGEBLADE: String = "res://src/resources/items/guinsoos_rageblade/data.tres"
const ITEM_DATA_INFINITY_EDGE: String = "res://src/resources/items/infinity_edge/data.tres"
const ITEM_DATA_IMMORTAL_SHIELDBOW: String = "res://src/resources/items/immortal_shieldbow/data.tres"
const ITEM_DATA_BLOODTHIRSTER: String = "res://src/resources/items/bloodthirster/data.tres"
const ITEM_DATA_ESSENCE_REAVER: String = "res://src/resources/items/essence_reaver/data.tres"

const ITEM_DATA_SERPENTS_FANG: String = "res://src/resources/items/serpents_fang/data.tres"
const ITEM_DATA_EDGE_OF_NIGHT: String = "res://src/resources/items/edge_of_night/data.tres"
const ITEM_DATA_VOLTAIC_CYCLOSWORD: String = "res://src/resources/items/voltaic_cyclosword/data.tres"
const ITEM_DATA_HUBRIS: String = "res://src/resources/items/hubris/data.tres"
const ITEM_DATA_AXIOM_ARC: String = "res://src/resources/items/axiom_arc/data.tres"
const ITEM_DATA_SERYLDAS_GRUDGE: String = "res://src/resources/items/seryldas_grudge/data.tres"

const ITEM_DATA_NASHORS_TOOTH: String = "res://src/resources/items/nashors_tooth/data.tres"
const ITEM_DATA_LICH_BANE: String = "res://src/resources/items/lich_bane/data.tres"
const ITEM_DATA_RABADONS_DEATHCAP: String = "res://src/resources/items/rabadons_deathcap/data.tres"
const ITEM_DATA_SHADOWFLAME: String = "res://src/resources/items/shadowflame/data.tres"
const ITEM_DATA_VOID_STAFF: String = "res://src/resources/items/void_staff/data.tres"
const ITEM_DATA_LIANDRYS_TORMENT: String = "res://src/resources/items/liandrys_torment/data.tres"
const ITEM_DATA_SCEPER_OF_BONKING: String = "res://src/resources/items/scepter_of_bonking/data.tres"
const ITEM_DATA_MORELLONOMICON: String = "res://src/resources/items/morellonomicon/data.tres"
const ITEM_DATA_MALIGNANCE: String = "res://src/resources/items/malignance/data.tres"
const ITEM_DATA_STORMSURGE: String = "res://src/resources/items/stormsurge/data.tres"
const ITEM_DATA_MEJAIS_SOULSTEALER: String = "res://src/resources/items/mejais_soulstealer/data.tres"
const ITEM_DATA_ROD_OF_AGES: String = "res://src/resources/items/rod_of_ages/data.tres"
const ITEM_DATA_ARCHANGELS_STAFF: String = "res://src/resources/items/archangels_staff/data.tres"
const ITEM_DATA_SERAPHS_EMBRACE: String = "res://src/resources/items/seraphs_embrace/data.tres"

const RUNE_DATA_PRESS_THE_ATTACK: String = "res://src/resources/runes/press_the_attack/data.tres"
const RUNE_DATA_LETHAL_TEMPO: String = "res://src/resources/runes/lethal_tempo/data.tres"
const RUNE_DATA_FLEET_FOOTWORK: String = "res://src/resources/runes/fleet_footwork/data.tres"
const RUNE_DATA_CONQUEROR: String = "res://src/resources/runes/conqueror/data.tres"
const RUNE_DATA_ELECTROCUTE: String = "res://src/resources/runes/electrocute/data.tres"
